specification:
  products:
    - ga_ls5t_ard_3
    - ga_ls7e_ard_3
    - ga_ls8c_ard_3
  measurements: ['nbart_green', 'nbart_red', 'nbart_nir', 'nbart_swir_1', 'nbart_swir_2']
  measurement_renames:
    nbart_green: green
    nbart_red: red
    nbart_nir: nir
    nbart_swir_1: swir1
    nbart_swir_2: swir2

  aws_unsigned: True
  transform: fc.virtualproduct.FractionalCover
  transform_url: 'https://github.com/GeoscienceAustralia/fc/'
  override_product_family: ard
  basis: nbart_green

  transform_args_per_product:
    ga_ls8c_ard_3:
      regression_coefficients:
        blue:
          - 4.1
          - 0.97470
        green:
          - 28.9
          - 0.99779
        red:
          - 27.4
          - 1.00446
        nir:
          - 0.4
          - 0.98906
        swir1:
          - 25.6
          - 0.99467
        swir2:
          - -32.7
          - 1.02551

output:
  location: /tmp/alchemist
  nodata: 255
  preview_image:
    red: bs
    green: pv
    blue: npv
  explorer_url: https://explorer.dev.dea.ga.gov.au
  write_data_settings:
    overview_resampling: average
  reference_source_dataset: True
  write_stac: True
  inherit_geometry: True

  metadata:
    product_family: fc
    producer: ga.gov.au
    dataset_version: 2.5.0
    collection_number: 3
    naming_conventions: dea_c3

  properties:
    dea:dataset_maturity: interim

processing:
  dask_chunks:
    x: -1
    y: 4096
