specification:
  product: ga_ls5t_ard_3
  measurements: ['nbart_blue', 'nbart_green', 'nbart_red', 'nbart_nir', 'nbart_swir_1', 'nbart_swir_2', 'oa_fmask']
  measurement_renames:
    oa_fmask: fmask
  transform: wofs.virtualproduct.WOfSClassifier
  override_product_family: ard
  basis: nbart_green

  transform_args:
    dsm_path:  's3://dea-non-public-data/dsm/dsm1sv1_0_Clean.tiff'

output:
  location: /tmp/alchemist
  nodata: 1
  dtype: uint8

  write_data_settings:
    overview_resampling: mode

  metadata:
    product_family: wo
    producer: ga.gov.au
    dataset_version: 1.6.0
    collection_number: 3

  properties:
    dea:dataset_maturity: interim

processing:
  dask_chunks:
    x: 600
    y: 600
